name: "Continuous Integration"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  tests:
    name: OS ${{ matrix.os }}, python ${{ matrix.python-version }}, ${{ matrix.uv-resolution }} dependencies
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.13"]
        uv-resolution:
          - "lowest-direct"
          - "highest"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      # install all requirements. Note that the full requirements are installed separately
      # so the job does not fail if one of the packages cannot be installed. This allows
      # testing the package for newer python version even when some of the optional
      # packages are not yet available.
      run: |
        python -m pip install --upgrade pip
        uv pip install -r requirements.txt --resolution ${{ matrix.uv-resolution }}
        cat tests/requirements_full.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -I % sh -c "uv pip install % --resolution ${{ matrix.uv-resolution }} || true"
        uv pip install -r tests/requirements.txt --resolution ${{ matrix.uv-resolution }}

    - name: Test with pytest
      env:
        NUMBA_WARNINGS: 1
        MPLBACKEND: agg
      run: |
        uv pip install pytest --resolution ${{ matrix.uv-resolution }}
        cd scripts
        python run_tests.py --unit --parallel

    - name: Test types with mypy
      continue-on-error: true
      run: |
        python -m mypy --config-file pyproject.toml --pretty --package emulsim
