name: "Build documentation"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  docs:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
